version: '3.8'

services:

  artifactory:
    image: artifactory:7.46.11
    build:
      context: .
      dockerfile: Dockerfile
    container_name: artifactory
    ports:
      - 8081:8081
      - 8082:8082
    # volumes:
    #   - ${HOST_PROJECT_PATH}/datadir:/var/opt/jfrog/artifactory
    # default username and password
    # admin password
