version: '3.8'

services:

  sftp:
    image: atmoz/sftp
    container_name: sftp
    volumes:
      - ${HOST_PROJECT_PATH}/upload:/home/foo/upload
    ports:
      - "2222:22"
    command: foo:pass:1001
